### PR TITLE
NCD, Progress Report - Patient Progress pane

### PR DESCRIPTION
**Pull request by anvmn**
#470

### CODE REVIEW

**Comment by anvmn** [comment]
Peek 2022-09-28 22-49

**Comment by anvmn** [comment]
Selection_1143

**Comment by anvmn** [comment]
Selection_1146

**Comment by anvmn** [comment]
@AronNovak please review

Note: @todos are completed at #493

**Review by AronNovak — APPROVED** [review]
Nice job with the SVG part :+1:

**Pull request merged**
