### PR TITLE
Random Blood Sugar lab with dual option for entering results + progress report presentation

### PR DESCRIPTION
**Pull request by anvmn**
#547
#417 (https://github.com/TIP-Global-Health/eheza-app/issues/417#issuecomment-1351953413)

### CODE REVIEW

**Comment by anvmn** [comment]
Peek 2022-12-14 22-16

**Comment by anvmn** [comment]
Peek 2022-12-15 14-53

**Comment by anvmn** [comment]
Selection_1414

**Comment by anvmn** [comment]
@mariano-dagostino please review

**Review by mariano-dagostino — APPROVED** [review]

**Pull request merged**
