### PR TITLE
ANC Subsequent Visit - Labs Section Progress Report 

### PR DESCRIPTION
**Pull request by anvmn**
#267

### CODE REVIEW

**Comment by anvmn** [comment]
Peek 2022-06-20 12-48

**Comment by anvmn** [comment]
Selection_855
Selection_856

**Comment by anvmn** [comment]
Selection_857

**Comment by anvmn** [comment]
Demo:

Peek 2022-06-21 21-05

**Comment by anvmn** [comment]
@mariano-dagostino please review

**Review by mariano-dagostino — APPROVED** [review]

**Pull request merged**
