### PR TITLE
Stock Management - Main Dashboard

### PR DESCRIPTION
**Pull request by anvmn**
#641

### CODE REVIEW

**Comment by anvmn** [comment]
Selection_1651

**Comment by anvmn** [comment]
Peek 2023-03-05 23-30

**Comment by anvmn** [comment]
Selection_1717

**Review by mariano-dagostino — APPROVED** [review]
Looks good, but travis is red.

**Comment by anvmn** [comment]
Reran travis, and it's green now. Merging...

**Pull request merged**
