### PR TITLE
Support latest DDEV

### PR DESCRIPTION
**Pull request by AronNovak**
#1125

### CODE REVIEW

**Comment by AronNovak** [comment]
@anvmn 
I am still blocked by https://github.com/ryan-haskell/date-format/issues/40 , but it seems it's out of scope, as it was happening earlier too, before DDEV upgrade.
Could you please test locally if all frontend tooling works on your end?

**Comment by amitaibu** [comment]
I get an error on `ddev gulp`

```
/usr/local/lib/node_modules/gulp/node_modules/yargs-parser/build/index.cjs:1007
        throw Error(`yargs parser supports a minimum Node.js version of ${minNodeVersion}. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions`);
        ^

Error: yargs parser supports a minimum Node.js version of 10. Read our version support policy: https://github.com/yargs/yargs-parser#supported-nodejs-versions
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/yargs-parser/build/index.cjs:1007:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/yargs/build/index.cjs:2855:16)
    at Module._compile (module.js:569:30)
```

**Comment by amitaibu** [comment]
`gulp` (without `ddev` prefix) does seem to run 

image

**Comment by AronNovak** [comment]
@amitaibu Those work well for me, the issue is that you need to clean up non-compatible node modules first:
```
rm -rf client/node_modules
cp .ddev/config.local.yaml.example .ddev/config.local.yaml
ddev restart
ddev gulp
```

I think you end up with the:
```
-- CORRUPT PACKAGE DATA --------------------------------------------------------

I downloaded the source code for ryannhg/date-format 2.3.0 from:

    https://github.com/ryannhg/date-format/zipball/2.3.0/

But it looks like the hash of the archive has changed since publication:

  Expected: 70c67866fed499bec685f43f23fea279556757f2
    Actual: 86534146f5a550bb8e87b87a7484ea5732090bb5
```

error.

**Comment by AronNovak** [comment]
https://discourse.elm-lang.org/t/ryannhg-packages-renamed-to-ryan-haskell/9705/13 - this is also related.

**Comment by AronNovak** [comment]
image

We will need to upgrade `gampleman/elm-visualization` to get rid of the obsolete dependency likely.

**Comment by amitaibu** [comment]
> We will need to upgrade gampleman/elm-visualization to get rid of the obsolete dependency likely.

I see there's a fork for it - https://discourse.elm-lang.org/t/ryannhg-packages-renamed-to-ryan-haskell/9705/10 , with this change

**Comment by amitaibu** [comment]
Actually, original package already has this change

image

**Comment by amitaibu** [comment]
@AronNovak I've created https://github.com/TIP-Global-Health/eheza-app/pull/1199

**Review by anvmn — APPROVED** [review]

**Pull request merged**
