### PR TITLE
ANC Subsequent visits -  Continued Illness + Outside Care multiselect

### PR DESCRIPTION
**Pull request by anvmn**
#263 
#257

### CODE REVIEW

**Comment by anvmn** [comment]
**Demo** - patient with repeated Urinary Tract Infection symptoms refered to hosipital :


Peek 2022-05-22 15-50

**Comment by anvmn** [comment]
@mariano-dagostino please review

**Comment by anvmn** [comment]
Peek 2022-05-25 00-00

**Comment by anvmn** [comment]
@mariano-dagostino please review

**Review by mariano-dagostino — APPROVED** [review]

**Pull request merged**
