### PR TITLE
HC Dashboard - NCD 

### PR DESCRIPTION
**Pull request by anvmn**
#968 
#969 
#970

### CODE REVIEW

**Comment by anvmn** [comment]
Selection_066

**Comment by anvmn** [comment]
Selection_067

**Comment by anvmn** [comment]
Selection_069

**Comment by anvmn** [comment]
Peek 2023-12-14 23-14

**Comment by anvmn** [comment]
Selection_076

**Comment by anvmn** [comment]
Selection_078

**Comment by anvmn** [comment]
Selection_086

**Review by mariano-dagostino — APPROVED** [review]

**Pull request merged**
