### PR TITLE
Redesign calendar widget

### PR DESCRIPTION
**Pull request by anvmn**
#13

### CODE REVIEW

**Comment by anvmn** [comment]
### Demo:

Peek 2021-11-25 16-09

**Comment by anvmn** [comment]
@adamhstewart @isapisa @jeanette-pelizzon ^^

**Comment by isapisa** [comment]
@anvmn I think the colour for a selected date should change, but deferring to @jeanette-pelizzon

**Comment by jeanette-pelizzon** [comment]
Can we make the dates all white or grey even before the year is selected? And round out the edges of the box - it's super harsh looking. 

Date picked see below: 

Screen Shot 2021-11-25 at 1 18 46 PM

**Comment by anvmn** [comment]
@jeanette-pelizzon like this?

Peek 2021-11-25 22-49

**Comment by jeanette-pelizzon** [comment]
Getting feedback on Wednesday for this and will report back with changes

**Comment by anvmn** [comment]
Peek 2021-12-21 22-09

**Comment by anvmn** [comment]
Peek 2021-12-22 12-09

**Comment by anvmn** [comment]
Peek 2021-12-22 13-15

**Comment by anvmn** [comment]
Peek 2021-12-22 13-29

**Comment by anvmn** [comment]
Peek 2021-12-22 14-02

**Comment by anvmn** [comment]
Peek 2021-12-22 14-23

**Comment by anvmn** [comment]
@mariano-dagostino please review

**Review by mariano-dagostino — COMMENTED** [review]
@anvmn Looks good. There is an small issue I've seen in the recordings. Somewhere there is a padding/marging that changes the size of the column where day is placed. When you select the number in the popup. It adds 1px on each side from what I can see...

**Comment by anvmn** [comment]
Thanks @mariano-dagostino. I'll see about that.

**Pull request merged**
