### PR TITLE
Child scorecard encounter - progress report

### PR DESCRIPTION
**Pull request by anvmn**
#954

### CODE REVIEW

**Comment by anvmn** [comment]
Peek 2023-11-27 21-08

**Review by mariano-dagostino — APPROVED** [review]
@anvmn Looks good, tests are failing.

**Comment by anvmn** [comment]
@mariano-dagostino 

>  tests are failing.

Yeah, same old story of simpletest getting stuck.

Selection_011

I sometimes have to restart it several times before it turns green.
@AronNovak any idea what might be the problem?

**Comment by AronNovak** [comment]
@anvmn https://github.com/TIP-Global-Health/eheza-app/pull/965/files - I started to experiment with this.

**Pull request merged**
