### PR TITLE
Group Education - Dashboard stats presentation

### PR DESCRIPTION
**Pull request by anvmn**
#1096

### CODE REVIEW

**Comment by anvmn** [comment]
### CHW:

Selection_392


### Nurse:

Selection_394

**Comment by anvmn** [comment]
Selection_393

**Comment by anvmn** [comment]
### CHW 

Peek 2024-04-10 12-22_

**Comment by anvmn** [comment]
### Nurse

Peek 2024-04-10 12-27

**Review by AronNovak — APPROVED** [review]

**Comment by AronNovak** [comment]
```
[33mException Notice     hedley_stats.modu 3741 hedley_stats_add_patient_details() 
[0m    Trying to access array offset on value of type null
```

Likely a real failure.

**Pull request merged**
