### PR TITLE
Input dates beyond current limits on LMP Calendar

### PR DESCRIPTION
**Pull request by Diama1**
#589

### CODE REVIEW

**Comment by Diama1** [comment]
calendar

**Review by anvmn — CHANGES_REQUESTED** [review]
@Diama1 

1. Please implement per requirements at https://github.com/TIP-Global-Health/eheza-app/issues/589#issuecomment-1385110513
2. After the change, make sure that LMP content gets properly saved on backend.

**Comment by Diama1** [comment]
calendar

Screenshot from 2023-01-17 14-14-20

**Review by anvmn — CHANGES_REQUESTED** [review]
https://github.com/TIP-Global-Health/eheza-app/issues/589#issuecomment-1385368394

**Comment by Diama1** [comment]
lmp

Screenshot from 2023-02-20 14-32-24

**Comment by anvmn** [comment]
Replaced by #801.

**Pull request closed without merging**
