### PR TITLE
NCDA report addaptations after restructuring

### PR DESCRIPTION
**Pull request by anvmn**
#521
#525
#518

### CODE REVIEW

**Comment by anvmn** [comment]
Selection_1348

**Comment by anvmn** [comment]
Peek 2022-12-01 15-41

**Comment by anvmn** [comment]
Selection_1351

**Comment by anvmn** [comment]
@mariano-dagostino please review

**Review by mariano-dagostino — APPROVED** [review]
@anvmn Looks good.

**Pull request merged**
