### PR TITLE
Scalability test

### PR DESCRIPTION
**Pull request by AronNovak**
## Status
image

### CODE REVIEW

**Comment by AronNovak** [comment]
image
First working version of patient creation via puppeteer.

**Comment by AronNovak** [comment]
https://stackoverflow.com/questions/59273294/how-to-upload-file-with-js-puppeteer - to put pressure on the storage + bw, I am going to upload a photo for every patient, that's the next action.

**Comment by AronNovak** [comment]
Or https://pub.dev/documentation/puppeteer/latest/puppeteer/FileChooser-class.html could work with DropZone

**Comment by AronNovak** [comment]
image
image

**Comment by AronNovak** [comment]
Yesterday I could successfully execute a realistic stress test round, so the code is basically ready.

**Comment by AronNovak** [comment]
@anvmn ^^

**Review by anvmn — APPROVED** [review]
Looks good to me

**Pull request merged**
