### PR TITLE
Calendar widget - allow defining default selection

### PR DESCRIPTION
**Pull request by anvmn**
#13

Per https://github.com/TIP-Global-Health/eheza-app/issues/13#issuecomment-1022313884

### CODE REVIEW

**Comment by anvmn** [comment]
### Immunisation demo:
Peek 2022-02-01 15-22

**Comment by anvmn** [comment]
### LMP Demo:
Peek 2022-02-01 15-13

**Comment by anvmn** [comment]
### Lab tests demo:

Peek 2022-02-01 14-53

**Comment by anvmn** [comment]
@mariano-dagostino please review

**Review by mariano-dagostino — APPROVED** [review]

**Pull request merged**
