### PR TITLE
Mac compatibility

### PR DESCRIPTION
**Pull request by AronNovak**
#531

### CODE REVIEW

**Review by anvmn — APPROVED** [review]

**Review by anvmn — APPROVED** [review]

**Comment by AronNovak** [comment]
@adamhstewart I'd only merge if you'd test it on your side, that on the latest commit of this branch, you are able to `ddev restart` and the client works well on your local.

**Comment by adamhstewart** [comment]
@smericle  going to assign to you to test on a Mac M2 device.

**Comment by smericle** [comment]
I got the front end to run locally on my M2 Macbook. I had to increase the allocated memory for Docker and with some testing found that Docker needed at least 7GB to get the front end to run correctly (at least on my device).

**Review by smericle — COMMENTED** [review]
I got the front end to run locally on my M2 Macbook. I had to increase the allocated memory for Docker and with some testing found that Docker needed at least 7GB to get the front end to run correctly (at least on my device).

**Review by adamhstewart — APPROVED** [review]
per @smericle 's tests

**Pull request merged**
