### PR TITLE
DDEV - Nodejs test

### PR DESCRIPTION
**Pull request by AronNovak**
https://github.com/drud/ddev/issues/4499

### CODE REVIEW

**Comment by AronNovak** [comment]
```
Successfully started eheza-app 
Project can be reached at https://eheza-app.ddev.site:4443 https://127.0.0.1:32856 
 aaron   ddev-nodejs  ~  gizra  eheza-app  ddev --version
ddev version v1.21.5-alpha1
 aaron   ddev-nodejs  ~  gizra  eheza-app  ddev gulp
[05:10:09] Using gulpfile /var/www/html/client/gulpfile.js
[05:10:09] Starting 'build'...
[05:10:09] Starting 'clean:dev'...
[05:10:09] Starting 'watch'...
[05:10:09] Finished 'watch' after 61 ms
[05:10:09] Finished 'clean:dev' after 112 ms
[05:10:09] Starting 'styles'...
[05:10:09] Starting 'zscore'...
[05:10:09] Starting 'copy:bower'...
[05:10:09] Starting 'copy:images'...
[05:10:09] Starting 'copy:favicon'...
[05:10:09] Starting 'copy:fonts'...
[05:10:09] Starting 'elm-init'...
[05:10:09] Finished 'elm-init' after 24 μs
[05:10:09] Starting 'version'...
[05:10:09] Finished 'version' after 71 ms
[05:10:09] Starting 'elm'...
```

**Comment by AronNovak** [comment]
^^ @anvmn We will be able to revert the workaround for node with the coming DDEV version.

**Comment by anvmn** [comment]
Thanks @AronNovak

**Comment by anvmn** [comment]
@AronNovak 

I suppose we can close this one, right?

**Pull request closed without merging**
